/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'zafu' at '2/20/17 4:16 PM' with Gradle 2.3
 *
 * @author zafu, @date 2/20/17 4:16 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
