import org.testng.annotations.Test;

import static org.testng.AssertJUnit.assertTrue;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'zafu' at '2/20/17 4:16 PM' with Gradle 2.3
 *
 * @author zafu, @date 2/20/17 4:16 PM
 */
public class LibraryTest {
    @Test
    public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
